signin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'signin'
urlpatterns = [
    path('', views.index, name='index'),

    path('signin/', views.signin_page, name='signin_default'),
    path('signin/<str:session>/', views.signin_page, name='signin_session'),

    path('graph/', views.graph_events_page, name='graph'),
    path('graph_people/', views.graph_people_page, name='graph_people'),

    path('spinner/', views.spinner_page, name='spinner'),

    path('options/', views.options_page, name='options'),

    path('api/signin/', views.SignInHandler.as_view(), name='api_signin'),

    path('api/graph_events/', views.GraphEventsHandler.as_view(), name='api_graph_events'),
    path('api/graph_people/', views.GraphPeopleHandler.as_view(), name='api_graph_people'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

signinwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('signin.urls')),
    path('admin/', admin.site.urls),
]

signin/models.py
from django.db import models
from django.db.models.functions import Upper, Concat
from django.db.models import Index, UniqueConstraint
from django.contrib import admin
from django.utils import timezone
from django.core.validators import RegexValidator
from simple_history.models import HistoricalRecords


class Session(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(
        max_length=100,
        unique=True,
        validators=[
            RegexValidator(
                '[a-z0-9_]',
                message="Only lower letters, numbers and underscores are allowed."
            )
        ])

    sign_in_time = models.TimeField(
        help_text="The time when you expect people to start signing in to this session."
    )
    sign_out_time = models.TimeField(
        help_text="The time when you expect people to be signing out of this session "
                  "instead of signing in."
    )
    end_time = models.TimeField(
        help_text="The time when you expect everyone to have left, and will no longer need anyone "
                  "to sign in/out."
    )

    history = HistoricalRecords()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("sign_in_time",)
        indexes = [
            Index(fields=["sign_in_time"])
        ]


class ActivePersonManager(models.Manager):
    """
    Object manager which only returns people that are not hidden
    """
    def get_queryset(self):
        return super().get_queryset().filter(hidden=False)


class Person(models.Model):
    first_name = models.CharField(max_length=100, verbose_name="First Name")
    last_name = models.CharField(max_length=100, verbose_name="Last Name")

    emergency_contact_first_name = models.CharField(max_length=100, blank=True)
    emergency_contact_last_name = models.CharField(max_length=100, blank=True)
    emergency_contact_phone_number = models.CharField(max_length=20, blank=True)

    media_permission = models.BooleanField(
        default=False,
        verbose_name="Do you give media permission?"
    )

    sessions = models.ManyToManyField(Session)

    hidden = models.BooleanField(default=False)
    date_added = models.DateTimeField(default=timezone.now)

    objects = models.Manager()
    actives = ActivePersonManager()

    history = HistoricalRecords()

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "People"

        # sort by last name, then first name, ignoring all case
        ordering = [Upper('last_name'), Upper('first_name')]

        constraints = [
            UniqueConstraint(
                Concat(Upper("last_name"), Upper("first_name")),
                name="person_name",
                violation_error_message="Person with this name already exists."
            )
        ]

        indexes = [
            Index(Upper('last_name'), name='idx_person_last_name')
        ]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    @property
    @admin.display
    def name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    @admin.display
    def emergency_contact_name(self):
        return f"{self.emergency_contact_first_name} {self.emergency_contact_last_name}"

    def save(self, *args, **kwargs):
        """
        Ensure names are in correct case (may break names with capital in the middle,
        e.g. MacDonald)
        """
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()
        super().save(*args, **kwargs)


class Signin(models.Model):
    is_signin = models.BooleanField(choices=[
        (True, "Sign in"),
        (False, "Sign out")
    ], verbose_name="Sign In/Out")

    date = models.DateTimeField(default=timezone.now)

    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "Sign In/Out"
        ordering = ('-date',)
        indexes = [
            Index(fields=['-date'])
        ]

    def __str__(self):
        return f"{self.person} - {'Sign In' if self.is_signin else 'Sign Out'}"

signin/views.py
from django.urls import reverse
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseNotFound
from django.contrib.admin.views.decorators import staff_member_required
from rest_framework.views import APIView
from rest_framework.request import Request
from .models import Person, Session, Signin
from .graphing import graph_people, graph_events, get_last_event_num
from .sessions import get_default_session, get_people_signin_status, get_people_by_session, \
    is_sign_in_time, get_people_for_spinner, get_active_sessions


def index(request):
    return HttpResponseRedirect(reverse('signin:signin_default'))


@staff_member_required
def signin_page(request, *args, **kwargs):
    if "session" in kwargs:
        try:
            session = Session.objects.get(code=kwargs["session"].lower())
        except Session.DoesNotExist:
            return HttpResponseNotFound(f"Session '{kwargs['session']}' does not exist")

    else:
        # No session provided, so default to one (currently arbitrary)
        session = get_default_session()
        return HttpResponseRedirect(reverse('signin:signin_session', args=[session.code]))

    context = {
        "people": get_people_signin_status(session),
        "current_session": session,
        "all_sessions": Session.objects.all(),
        "is_sign_in_time": is_sign_in_time(session)
    }

    return render(request, 'signin/signin.html', context)


@staff_member_required
def graph_events_page(request):
    context = {
        "all_sessions": Session.objects.all(),
    }
    return render(request, 'signin/graph_events.html', context)


@staff_member_required
def graph_people_page(request):
    context = {
        "all_sessions": Session.objects.all(),
        "people_by_session": get_people_by_session()
    }
    return render(request, 'signin/graph_people.html', context)


@staff_member_required
def options_page(request):
    context = {
        "all_sessions": Session.objects.all(),
    }
    return render(request, 'signin/options.html', context)


@staff_member_required
def spinner_page(request):
    context = {
        "all_sessions": Session.objects.all(),
        "people": get_people_for_spinner(),
    }
    return render(request, 'signin/spinner.html', context)


class SignInHandler(APIView):
    """
    Handles Sign In/Out requests.
    """
    @staticmethod
    def get(request: Request):
        """
        Handles requests to get the list of people and their signin status.
        """
        session = Session.objects.get(code=request.query_params["session"].lower())

        return JsonResponse(get_people_signin_status(session))

    @staticmethod
    def post(request: Request):
        """
        Handles requests to sign somebody in/out.
        """
        try:
            person = Person.objects.get(pk=request.data['pk'])
            session = Session.objects.get(code=request.data['session'])
        except (ValueError, Person.DoesNotExist, Session.DoesNotExist):
            return JsonResponse({"success": "false"})

        Signin.objects.create(
            is_signin=request.data['is_signin'],
            person=person,
            session=session
        )

        return JsonResponse({"success": "true", "person": person.name})


class GraphEventsHandler(APIView):
    @staticmethod
    def put(request: Request):
        session = Session.objects.get(code=request.data["session"])
        events_graphs = graph_events(session)
        last_event = get_last_event_num(session)
        return JsonResponse({"events_graph": events_graphs, "last_event": last_event})


class GraphPeopleHandler(APIView):
    @staticmethod
    def put(request: Request):
        session = Session.objects.get(code=request.data["session"])
        people_graph = graph_people(request.data['people_ids'], session)
        return JsonResponse({"people_graph": people_graph})

signin/templates/signin/graph.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Graph People</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<style>
    ul {
      -webkit-column-count: 3; /* Chrome, Safari, Opera */
      -moz-column-count: 3; /* Firefox */
      column-count: 3;
    }
    @media (max-width: 576px) {
      ul {
        -webkit-column-count: 1; /* Chrome, Safari, Opera */
        -moz-column-count: 1; /* Firefox */
        column-count: 1;
      }
    }
</style>
<body>
    {% include "signin/navbar.html" %}
    <div class="container-md my-3 px-3" id="container">
        <div class="row">
            <h2>Generate Graph</h2>
            <p>Select the people that you would like to include in the graph.</p>
        </div>
        <form>
            <ul class="list-unstyled">
                {% for pk, name in people.items %}
                <li>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="{{ pk }}" title="{{ name }}" id="{{ pk }}">
                        <label class="form-check-label" for="{{ pk }}">{{ name }}</label>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div class="my-3">
                <button type="button" class="btn btn-primary" onclick="graph()">Graph</button>
                <button type="button" class="btn btn-secondary" onclick="selectAll()">Select All</button>
                <p hidden class="text-danger" id="error"><small>You must select at least one person</small></p>
            </div>
        </form>
        <iframe width="100%" height="700px" id="people_graph"></iframe>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script>
        function selectAll() {
            for (let checkbox of document.querySelectorAll('input[type="checkbox"]')) {
                checkbox.checked = true;
            }
        }

        function graph() {
            let people_ids = Array.from(document.querySelectorAll('input[type="checkbox"]:checked')).map((checkbox) => {return checkbox.value;});
            if (people_ids.length < 1) {
                document.getElementById('error').hidden = false;
                return false;
            } else {
                document.getElementById('error').hidden = true;
            }
            fetch("{% url 'signin:graph_people_request' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    "X-CSRFToken": '{{csrf_token}}'
            },
                credentials: 'same-origin',
                body: JSON.stringify({people_ids: people_ids}),
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                document.getElementById('people_graph').srcdoc = data.people_graph;
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        }
    </script>
</body>
</html>

signin/templates/signin/graph_events.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Graph</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="manifest" href="{% static 'app.webmanifest' %}">
</head>
<body>
    {% include "signin/navbar.html" %}
    <div class="container-md my-3 px-3" id="container">
        <div class="row">
            <h2>Number of Attendees By Event</h2>
            <p>Select the session you would like to graph.</p>
            <div class="d-block">
            {% for session in all_sessions %}
                <button id="{{ session.code }}" onclick="graph(this)" type="button" class="btn btn-primary">{{ session.name }}</button>
            {% endfor %}
            </div>
        </div>
        <iframe width="100%" height="700px" id="events_graph"></iframe>
        <p id="last_event"></p>
        <a href="/graph_people">Other Graph</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script>
        function graph(session_button) {
            fetch("{% url 'signin:api_graph_events' %}", {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    "X-CSRFToken": '{{csrf_token}}'
                },
                credentials: 'same-origin',
                body: JSON.stringify({
                    session: session_button.id
                })
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                document.getElementById('events_graph').srcdoc = data.events_graph;
                document.getElementById('last_event').innerText = `Number of people at last event: ${data.last_event}`;
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        }
    </script>
</body>
</html>

signin/templates/signin/graph_people.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Graph People</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="manifest" href="{% static 'app.webmanifest' %}">
</head>
<style>
    ul {
      -webkit-column-count: 3; /* Chrome, Safari, Opera */
      -moz-column-count: 3; /* Firefox */
      column-count: 3;
    }
    @media (max-width: 576px) {
      ul {
        -webkit-column-count: 1; /* Chrome, Safari, Opera */
        -moz-column-count: 1; /* Firefox */
        column-count: 1;
      }
    }
</style>
<body>
    {% include "signin/navbar.html" %}
    <div class="container-md my-3 px-3" id="container">
        <div class="row">
            <h2>Generate Graph</h2>
            <div class="d-block">
            {% for session in all_sessions %}
                <button value="{{ session.code }}" onclick="selectSession(this)" type="button" class="btn btn-primary">{{ session.name }}</button>
            {% endfor %}
            </div>
            <p class="hint" hidden>Select the people that you would like to include in the graph.</p>
        </div>
        <form>
            {% for session, people in people_by_session.items %}
            <ul class="list-unstyled session" id="{{ session }}" hidden>
                {% for pk, name in people.items %}
                <li>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="{{ pk }}" value="{{ pk }}" title="{{ name }}">
                        <label class="form-check-label" for="{{ pk }}">{{ name }}</label>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% endfor %}
            <div class="my-3 hint" hidden>
                <button type="button" class="btn btn-primary" onclick="graph()">Graph</button>
                <button type="button" class="btn btn-secondary" onclick="selectAllPeople()">Select All</button>
                <p hidden class="text-danger" id="error"><small>You must select at least one person</small></p>
            </div>
        </form>
        <iframe width="100%" height="700px" id="people_graph"></iframe>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script>
        let session = "";

        function selectSession(session_button) {
            for (const element of document.querySelectorAll(".hint")) {
                element.hidden = false;
            }

            // Hide other sessions and show selected session
            for (const element of document.querySelectorAll(".session")) {
                element.hidden = true;
            }
            document.getElementById(session_button.value).hidden = false;

            session = session_button.value;
        }

        function selectAllPeople() {
            const session_list = document.getElementById(session);
            for (const checkbox of session_list.querySelectorAll('input[type="checkbox"]')) {
                checkbox.checked = true;
            }
        }

        function graph() {
            const people_ids = Array.from(document.querySelectorAll('input[type="checkbox"]:checked'))
                .map((checkbox) => {return checkbox.value;});

            if (people_ids.length < 1) {
                document.getElementById('error').hidden = false;
                return false;
            } else {
                document.getElementById('error').hidden = true;
            }

            fetch("{% url 'signin:api_graph_people' %}", {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    "X-CSRFToken": '{{csrf_token}}'
            },
                credentials: 'same-origin',
                body: JSON.stringify({
                    session: session,
                    people_ids: people_ids
                }),
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                document.getElementById('people_graph').srcdoc = data.people_graph;
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        }
    </script>
</body>
</html>

signin/templates/signin/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                {% for session in all_sessions %}
                <a href="/signin/{{ session.code }}" class="nav-item nav-link {% if session.name == current_session.name %}active{% endif %}">{{ session.name }}</a>
                {% endfor %}
            </div>
            <div class="navbar-nav ms-auto">
                <div class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tools</a>
                  <div class="dropdown-menu dropdown-menu-end dropdown-menu-dark">
                      <a href="/graph" class="nav-item nav-link {% if page == 'graph' %}active{% endif %}">Graph</a>
                      <a href="/spinner" class="nav-item nav-link {% if page == 'spinner' %}active{% endif %}">Spinner</a>
                      <a href="/options" class="nav-item nav-link {% if page == 'options' %}active{% endif %}">Options</a>
                      <a href="/admin/signin/person" class="nav-item nav-link">Admin</a>
                  </div>
                </div>
            </div>
        </div>
    </div>
</nav>

signin/templates/signin/options.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Options</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="manifest" href="{% static 'app.webmanifest' %}">
</head>
<body>
    {% include "signin/navbar.html" %}
    <div class="container-md my-3 px-3">
        <h1>Options</h1>
        <div>
            <h4 class="mb-0">Appearance</h4>

            <label for="fontSize">Font Size:</label>
            <input id="fontSize" type="number" min="10" max="30">
            <p class="fst-italic mb-2">Default: 16</p>
            <br>
        </div>
        <div>
            <h4 class="mb-0">Spinner</h4>

            <label for="spinnerSpeed">Spinner Speed:</label>
            <input id="spinnerSpeed" type="number" min="100" max="500">
            <p class="fst-italic mb-2">Default: 500</p>

            <label for="spinnerResistance">Spinner Resistance:</label>
            <input id="spinnerResistance" type="number" min="0" max="500">
            <p class="fst-italic mb-2">Default: 100</p>

            <label for="spinnerMinDays">Min Days:</label>
            <input id="spinnerMinDays" type="number" min="0" max="500">
            <p class="fst-italic mb-2">Default: 20</p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script>
        const storage = window.localStorage;

        const fontSizeInputs = ["fontSize"];
        initialiseNumberInputs(fontSizeInputs, 16);

        const spinnerSpeedInputs = ["spinnerSpeed"];
        initialiseNumberInputs(spinnerSpeedInputs, 500);

        const spinnerResistanceInputs = ["spinnerResistance"];
        initialiseNumberInputs(spinnerResistanceInputs, 100);

        const spinnerMinDays = ["spinnerMinDays"];
        initialiseNumberInputs(spinnerMinDays, 20);

        /**
         * Automatically generates default values and event handlers for number inputs
         * @param {string[]} numberInputs The id of the number input elements whose values/event handlers will be initialised.
         * @param {number} defaultValue The default values for all the elements in numberInputs
         */
        function initialiseNumberInputs(numberInputs, defaultValue) {
            for (const numberInputID of numberInputs) {
                const numberInputElement = document.getElementById(numberInputID);
                let numberInputValue = storage.getItem(numberInputID);

                numberInputElement.value = (numberInputValue) ? numberInputValue : defaultValue;  // sets default to 16
                numberInputElement.addEventListener('change', (event) => {
                    numberInputValue = event.target.value;
                    storage.setItem(numberInputID, numberInputValue);
                });
            }
        }
    </script>
</body>
</html>

signin/templates/signin/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%  load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ current_session.name }} | Sign {% if is_sign_in_time %}In{% else %}Out{% endif %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'signin.css' %}" rel="stylesheet">
    <link rel="manifest" href="{% static 'app.webmanifest' %}">
</head>
<style>
    {% if is_sign_in_time %}
    input[type="checkbox"]:checked {
        opacity: 0.3;
    }
    label:has(+ input[type="checkbox"]:checked) {
        opacity: 0.4;
    }
    {% endif %}
</style>
<body>
    {% include "signin/navbar.html" %}
    <div class="container-md my-3 px-3">
        <h1>{{ current_session.name }}</h1>
        <p id="peopleCount" class="text-secondary">Signed In: ?</p>
        <div class="columns" id="peopleList">
            {% for pk, person in people.items %}
                <div class="form-check ps-0">
                    <label class="person-card form-check-label w-100 py-1 ps-2 mb-2 border border-1 rounded" for="{{ pk }}">{{ person.name }}</label>
                    <input class="form-check-input d-none" type="checkbox" id="{{ pk }}" value="{{ pk }}" title="{{ person.name }}" onclick="signIn(this)" {% if person.signed_in %}checked{% endif %}>
                </div>
            {% endfor %}
        </div>
    </div>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script>
        const api_signin_path = "{% url 'signin:api_signin' %}";
        const csrf_token = "{{csrf_token}}";
        const current_session_code = "{{ current_session.code }}";
    </script>
    <script src="{% static 'signin.js' %}"></script>
</body>
</html>

signin/templates/signin/spinner.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wheel Spinner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="preload" href="{% static 'spinner_font.woff2' %}" as="font" crossorigin="anonymous">
    <link rel="manifest" href="{% static 'app.webmanifest' %}">
    <style>
    @font-face {
        font-family: 'Amatic SC';
        font-style: normal;
        font-weight: 400;
        font-display: block;
        src:
            local("Amatic SC"),
            url("{% static 'spinner_font.woff2' %}") format("woff2");
    }

    .use-font, .chosen-person {
        font-family: "Amatic SC", system-ui;
    }

    .chosen-person {
        text-align: right;
        line-height: normal;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
        font-size: 4.5rem;
        cursor: grab;
        margin-bottom: 0;
        user-select: none;
        font-weight: bold;
    }
</style>
</head>
<body>
    {% include "signin/navbar.html" with current_session="" %}
    <div class="container-md my-3 px-3 position-relative">
        <div id="spinner_options">
            <h4>Spinner Options</h4>
            <div class="form-check form-switch">
                <input type="checkbox" class="form-check-input" id="signed_in_only" checked>
                <label for="signed_in_only" class="form-check-label">Signed In Only</label>
            </div>
            <div class="form-check form-switch">
                <input type="checkbox" class="form-check-input" id="filter_new" checked>
                <label for="filter_new" class="form-check-label">Filter Newcomers</label>
            </div>
            <div class="d-block">
            {% for session in all_sessions %}
                <button id="{{ session.code }}" type="button" class="btn btn-primary session">{{ session.name }}</button>
            {% endfor %}
            </div>
        </div>
        <div class="d-flex justify-content-center position-absolute">
            <button type="button" id="spin_button" class="btn btn-success btn-lg" style="z-index: 10" hidden>Spin!</button>
        </div>
        <div id="wheel-wrapper" class="vh-100 position-relative">
            <div class="position-absolute d-flex flex-column end-0" style="width: 28%" id="chosen_people"></div>
        </div>
        <p class="use-font">.</p>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous" defer></script>
    <script>
        const people = {{ people | safe }};
        const spinnerImage = "{% static 'spinner_center.svg' %}";
        const spinnerOverlayImage = "{% static 'spinner_border.svg' %}";
    </script>
    <script type="module" src="{% static 'spinner.js' %}"></script>
</body>
</html>